/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AccessStateTransitionType : Access State Transition Type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessStateTransitionType {
}

impl AccessStateTransitionType {
    /// Access State Transition Type.
    pub fn new() -> AccessStateTransitionType {
        AccessStateTransitionType {
        }
    }
}


