/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AmfEventSubsSyncInfo : AMF Event Subscriptions Information for synchronization



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmfEventSubsSyncInfo {
    #[serde(rename = "subscriptionList")]
    pub subscription_list: Vec<crate::models::AmfEventSubscriptionInfo>,
}

impl AmfEventSubsSyncInfo {
    /// AMF Event Subscriptions Information for synchronization
    pub fn new(subscription_list: Vec<crate::models::AmfEventSubscriptionInfo>) -> AmfEventSubsSyncInfo {
        AmfEventSubsSyncInfo {
            subscription_list,
        }
    }
}


