/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AmfEventType : Describes the supported event types of Namf_EventExposure Service



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmfEventType {
}

impl AmfEventType {
    /// Describes the supported event types of Namf_EventExposure Service
    pub fn new() -> AmfEventType {
        AmfEventType {
        }
    }
}


