/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AmfEventTrigger : Describes how AMF should generate the report for the event



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmfEventTrigger {
}

impl AmfEventTrigger {
    /// Describes how AMF should generate the report for the event
    pub fn new() -> AmfEventTrigger {
        AmfEventTrigger {
        }
    }
}


