/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AmfUpdatedEventSubscription : Represents a successful update on an AMF Event Subscription



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmfUpdatedEventSubscription {
    #[serde(rename = "subscription")]
    pub subscription: Box<crate::models::AmfEventSubscription>,
    #[serde(rename = "reportList", skip_serializing_if = "Option::is_none")]
    pub report_list: Option<Vec<crate::models::AmfEventReport>>,
}

impl AmfUpdatedEventSubscription {
    /// Represents a successful update on an AMF Event Subscription
    pub fn new(subscription: crate::models::AmfEventSubscription) -> AmfUpdatedEventSubscription {
        AmfUpdatedEventSubscription {
            subscription: Box::new(subscription),
            report_list: None,
        }
    }
}


