/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AmfEventNotification : Data within a AMF Event Notification request



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AmfEventNotification {
    #[serde(rename = "notifyCorrelationId", skip_serializing_if = "Option::is_none")]
    pub notify_correlation_id: Option<String>,
    #[serde(rename = "subsChangeNotifyCorrelationId", skip_serializing_if = "Option::is_none")]
    pub subs_change_notify_correlation_id: Option<String>,
    #[serde(rename = "reportList", skip_serializing_if = "Option::is_none")]
    pub report_list: Option<Vec<crate::models::AmfEventReport>>,
    #[serde(rename = "eventSubsSyncInfo", skip_serializing_if = "Option::is_none")]
    pub event_subs_sync_info: Option<Box<crate::models::AmfEventSubsSyncInfo>>,
}

impl AmfEventNotification {
    /// Data within a AMF Event Notification request
    pub fn new() -> AmfEventNotification {
        AmfEventNotification {
            notify_correlation_id: None,
            subs_change_notify_correlation_id: None,
            report_list: None,
            event_subs_sync_info: None,
        }
    }
}


