/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AppliedSmccType : Possible values are: - DNN_CC: Indicates the DNN based congestion control. - SNSSAI_CC: Indicates the S-NSSAI based congestion control. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppliedSmccType {
}

impl AppliedSmccType {
    /// Possible values are: - DNN_CC: Indicates the DNN based congestion control. - SNSSAI_CC: Indicates the S-NSSAI based congestion control. 
    pub fn new() -> AppliedSmccType {
        AppliedSmccType {
        }
    }
}


