/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// BaseRecord : Abstract base data type for UE data reporting records.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BaseRecord {
    /// string with format 'date-time' as defined in OpenAPI.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl BaseRecord {
    /// Abstract base data type for UE data reporting records.
    pub fn new(timestamp: String) -> BaseRecord {
        BaseRecord {
            timestamp,
        }
    }
}


