/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CmInfo : Represents the connection management state of a UE for an access type



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CmInfo {
    #[serde(rename = "cmState")]
    pub cm_state: Box<crate::models::CmState>,
    #[serde(rename = "accessType")]
    pub access_type: crate::models::AccessType,
}

impl CmInfo {
    /// Represents the connection management state of a UE for an access type
    pub fn new(cm_state: crate::models::CmState, access_type: crate::models::AccessType) -> CmInfo {
        CmInfo {
            cm_state: Box::new(cm_state),
            access_type,
        }
    }
}


