/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CollectiveBehaviourFilterType : Represents collective behaviour parameter type.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectiveBehaviourFilterType {
}

impl CollectiveBehaviourFilterType {
    /// Represents collective behaviour parameter type.
    pub fn new() -> CollectiveBehaviourFilterType {
        CollectiveBehaviourFilterType {
        }
    }
}


