/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CollectiveBehaviourInfo : Contains the collective behaviour information to be reported to the subscriber.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CollectiveBehaviourInfo {
    #[serde(rename = "colAttrib")]
    pub col_attrib: Vec<crate::models::PerUeAttribute>,
    /// Total number of UEs that fulfil a collective within the area of interest.
    #[serde(rename = "noOfUes", skip_serializing_if = "Option::is_none")]
    pub no_of_ues: Option<i32>,
    #[serde(rename = "appIds", skip_serializing_if = "Option::is_none")]
    pub app_ids: Option<Vec<String>>,
    #[serde(rename = "extUeIds", skip_serializing_if = "Option::is_none")]
    pub ext_ue_ids: Option<Vec<String>>,
    #[serde(rename = "ueIds", skip_serializing_if = "Option::is_none")]
    pub ue_ids: Option<Vec<String>>,
}

impl CollectiveBehaviourInfo {
    /// Contains the collective behaviour information to be reported to the subscriber.
    pub fn new(col_attrib: Vec<crate::models::PerUeAttribute>) -> CollectiveBehaviourInfo {
        CollectiveBehaviourInfo {
            col_attrib,
            no_of_ues: None,
            app_ids: None,
            ext_ue_ids: None,
            ue_ids: None,
        }
    }
}


