/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Exception : Represents the Exception information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Exception {
    #[serde(rename = "excepId")]
    pub excep_id: Box<crate::models::ExceptionId>,
    #[serde(rename = "excepLevel", skip_serializing_if = "Option::is_none")]
    pub excep_level: Option<i32>,
    #[serde(rename = "excepTrend", skip_serializing_if = "Option::is_none")]
    pub excep_trend: Option<Box<crate::models::ExceptionTrend>>,
}

impl Exception {
    /// Represents the Exception information.
    pub fn new(excep_id: crate::models::ExceptionId) -> Exception {
        Exception {
            excep_id: Box::new(excep_id),
            excep_level: None,
            excep_trend: None,
        }
    }
}


