/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Ipv6Prefix : String identifying an IPv6 address prefix formatted according to clause 4 of RFC 5952. IPv6Prefix data type may contain an individual /128 IPv6 address. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Ipv6Prefix {
}

impl Ipv6Prefix {
    /// String identifying an IPv6 address prefix formatted according to clause 4 of RFC 5952. IPv6Prefix data type may contain an individual /128 IPv6 address. 
    pub fn new() -> Ipv6Prefix {
        Ipv6Prefix {
        }
    }
}


