/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LadnInfo : LADN Information



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LadnInfo {
    #[serde(rename = "ladn")]
    pub ladn: String,
    #[serde(rename = "presence", skip_serializing_if = "Option::is_none")]
    pub presence: Option<Box<crate::models::PresenceState>>,
}

impl LadnInfo {
    /// LADN Information
    pub fn new(ladn: String) -> LadnInfo {
        LadnInfo {
            ladn,
            presence: None,
        }
    }
}


