/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LineType : Possible values are: - DSL: Identifies a DSL line - PON: Identifies a PON line 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LineType {
}

impl LineType {
    /// Possible values are: - DSL: Identifies a DSL line - PON: Identifies a PON line 
    pub fn new() -> LineType {
        LineType {
        }
    }
}


