/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LocationArea5G : Represents a user location area when the UE is attached to 5G.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationArea5G {
    /// Identifies a list of geographic area of the user where the UE is located.
    #[serde(rename = "geographicAreas", skip_serializing_if = "Option::is_none")]
    pub geographic_areas: Option<Vec<crate::models::GeographicArea>>,
    /// Identifies a list of civic addresses of the user where the UE is located.
    #[serde(rename = "civicAddresses", skip_serializing_if = "Option::is_none")]
    pub civic_addresses: Option<Vec<crate::models::CivicAddress>>,
    #[serde(rename = "nwAreaInfo", skip_serializing_if = "Option::is_none")]
    pub nw_area_info: Option<Box<crate::models::NetworkAreaInfo>>,
}

impl LocationArea5G {
    /// Represents a user location area when the UE is attached to 5G.
    pub fn new() -> LocationArea5G {
        LocationArea5G {
            geographic_areas: None,
            civic_addresses: None,
            nw_area_info: None,
        }
    }
}


