/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LocalOrigin : Indicates a Local origin in a reference system



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocalOrigin {
    #[serde(rename = "coordinateId", skip_serializing_if = "Option::is_none")]
    pub coordinate_id: Option<String>,
    #[serde(rename = "point", skip_serializing_if = "Option::is_none")]
    pub point: Option<Box<crate::models::GeographicalCoordinates>>,
}

impl LocalOrigin {
    /// Indicates a Local origin in a reference system
    pub fn new() -> LocalOrigin {
        LocalOrigin {
            coordinate_id: None,
            point: None,
        }
    }
}


