/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LocationFilter : Describes the supported filters of LOCATION_REPORT event type



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LocationFilter {
}

impl LocationFilter {
    /// Describes the supported filters of LOCATION_REPORT event type
    pub fn new() -> LocationFilter {
        LocationFilter {
        }
    }
}


