/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaStreamingAccessRecordAllOfResponseMessage {
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "responseCode")]
    pub response_code: i32,
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "size")]
    pub size: i32,
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "bodySize")]
    pub body_size: i32,
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
}

impl MediaStreamingAccessRecordAllOfResponseMessage {
    pub fn new(response_code: i32, size: i32, body_size: i32) -> MediaStreamingAccessRecordAllOfResponseMessage {
        MediaStreamingAccessRecordAllOfResponseMessage {
            response_code,
            size,
            body_size,
            content_type: None,
        }
    }
}


