/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaStreamingAccessRecordAllOfConnectionMetrics {
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "meanNetworkRoundTripTime")]
    pub mean_network_round_trip_time: f32,
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "networkRoundTripTimeVariation")]
    pub network_round_trip_time_variation: f32,
    /// Unsigned Integer, i.e. only value 0 and integers above 0 are permissible.
    #[serde(rename = "congestionWindowSize")]
    pub congestion_window_size: i32,
}

impl MediaStreamingAccessRecordAllOfConnectionMetrics {
    pub fn new(mean_network_round_trip_time: f32, network_round_trip_time_variation: f32, congestion_window_size: i32) -> MediaStreamingAccessRecordAllOfConnectionMetrics {
        MediaStreamingAccessRecordAllOfConnectionMetrics {
            mean_network_round_trip_time,
            network_round_trip_time_variation,
            congestion_window_size,
        }
    }
}


