/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Model5GsUserState : Describes the 5GS User State of a UE



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model5GsUserState {
}

impl Model5GsUserState {
    /// Describes the 5GS User State of a UE
    pub fn new() -> Model5GsUserState {
        Model5GsUserState {
        }
    }
}


