/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MsAccessActivityCollection : Contains Media Streaming access activity collected for an UE Application via AF.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsAccessActivityCollection {
    #[serde(rename = "msAccActs")]
    pub ms_acc_acts: Vec<crate::models::MediaStreamingAccessRecord>,
}

impl MsAccessActivityCollection {
    /// Contains Media Streaming access activity collected for an UE Application via AF.
    pub fn new(ms_acc_acts: Vec<crate::models::MediaStreamingAccessRecord>) -> MsAccessActivityCollection {
        MsAccessActivityCollection {
            ms_acc_acts,
        }
    }
}


