/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MsDynPolicyInvocationCollection : Contains the Media Streaming Dynamic Policy invocation collected for an UE Application via AF. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsDynPolicyInvocationCollection {
    #[serde(rename = "msDynPlyInvocs")]
    pub ms_dyn_ply_invocs: Vec<crate::models::DynamicPolicy>,
}

impl MsDynPolicyInvocationCollection {
    /// Contains the Media Streaming Dynamic Policy invocation collected for an UE Application via AF. 
    pub fn new(ms_dyn_ply_invocs: Vec<crate::models::DynamicPolicy>) -> MsDynPolicyInvocationCollection {
        MsDynPolicyInvocationCollection {
            ms_dyn_ply_invocs,
        }
    }
}


