/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MsNetAssInvocationCollection : Contains the Media Streaming Network Assistance invocation collected for an UE Application  via AF. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsNetAssInvocationCollection {
    #[serde(rename = "msNetAssInvocs")]
    pub ms_net_ass_invocs: Vec<crate::models::NetworkAssistanceSession>,
}

impl MsNetAssInvocationCollection {
    /// Contains the Media Streaming Network Assistance invocation collected for an UE Application  via AF. 
    pub fn new(ms_net_ass_invocs: Vec<crate::models::NetworkAssistanceSession>) -> MsNetAssInvocationCollection {
        MsNetAssInvocationCollection {
            ms_net_ass_invocs,
        }
    }
}


