/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// MsQoeMetricsCollection : Contains the Media Streaming QoE metrics information collected for an UE Application via AF. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MsQoeMetricsCollection {
    #[serde(rename = "msQoeMetrics")]
    pub ms_qoe_metrics: Vec<String>,
}

impl MsQoeMetricsCollection {
    /// Contains the Media Streaming QoE metrics information collected for an UE Application via AF. 
    pub fn new(ms_qoe_metrics: Vec<String>) -> MsQoeMetricsCollection {
        MsQoeMetricsCollection {
            ms_qoe_metrics,
        }
    }
}


