/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NefEventSubs : Represents an event to be subscribed and the related event filter information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NefEventSubs {
    #[serde(rename = "event")]
    pub event: Box<crate::models::NefEvent>,
    #[serde(rename = "eventFilter", skip_serializing_if = "Option::is_none")]
    pub event_filter: Option<Box<crate::models::NefEventFilter>>,
}

impl NefEventSubs {
    /// Represents an event to be subscribed and the related event filter information.
    pub fn new(event: crate::models::NefEvent) -> NefEventSubs {
        NefEventSubs {
            event: Box::new(event),
            event_filter: None,
        }
    }
}


