/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NefEventFilter : Represents event filter information for an event.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NefEventFilter {
    #[serde(rename = "tgtUe")]
    pub tgt_ue: Box<crate::models::TargetUeIdentification>,
    #[serde(rename = "appIds", skip_serializing_if = "Option::is_none")]
    pub app_ids: Option<Vec<String>>,
    #[serde(rename = "locArea", skip_serializing_if = "Option::is_none")]
    pub loc_area: Option<Box<crate::models::NetworkAreaInfo>>,
    #[serde(rename = "collAttrs", skip_serializing_if = "Option::is_none")]
    pub coll_attrs: Option<Vec<crate::models::CollectiveBehaviourFilter>>,
}

impl NefEventFilter {
    /// Represents event filter information for an event.
    pub fn new(tgt_ue: crate::models::TargetUeIdentification) -> NefEventFilter {
        NefEventFilter {
            tgt_ue: Box::new(tgt_ue),
            app_ids: None,
            loc_area: None,
            coll_attrs: None,
        }
    }
}


