/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NefEventExposureNotif : Represents notifications on network exposure event(s) that occurred for an Individual Network Exposure Event Subscription resource. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NefEventExposureNotif {
    #[serde(rename = "notifId")]
    pub notif_id: String,
    #[serde(rename = "eventNotifs")]
    pub event_notifs: Vec<crate::models::NefEventNotification>,
}

impl NefEventExposureNotif {
    /// Represents notifications on network exposure event(s) that occurred for an Individual Network Exposure Event Subscription resource. 
    pub fn new(notif_id: String, event_notifs: Vec<crate::models::NefEventNotification>) -> NefEventExposureNotif {
        NefEventExposureNotif {
            notif_id,
            event_notifs,
        }
    }
}


