/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NefEvent : Represents Network Exposure Events.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NefEvent {
}

impl NefEvent {
    /// Represents Network Exposure Events.
    pub fn new() -> NefEvent {
        NefEvent {
        }
    }
}


