/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NetworkAssistanceSession : A representation of a Network Assistance Session resource.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkAssistanceSession {
    /// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
    #[serde(rename = "naSessionId")]
    pub na_session_id: String,
    /// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
    #[serde(rename = "provisioningSessionId")]
    pub provisioning_session_id: String,
    #[serde(rename = "serviceDataFlowDescriptions")]
    pub service_data_flow_descriptions: Vec<crate::models::ServiceDataFlowDescription>,
    #[serde(rename = "mediaType", skip_serializing_if = "Option::is_none")]
    pub media_type: Option<Box<crate::models::MediaType>>,
    /// String chosen by the 5GMS AF to serve as an identifier in a resource URI.
    #[serde(rename = "policyTemplateId", skip_serializing_if = "Option::is_none")]
    pub policy_template_id: Option<String>,
    #[serde(rename = "requestedQoS", skip_serializing_if = "Option::is_none")]
    pub requested_qo_s: Option<Box<crate::models::M5QoSSpecification>>,
    #[serde(rename = "recommendedQoS", skip_serializing_if = "Option::is_none")]
    pub recommended_qo_s: Option<Box<crate::models::M5QoSSpecification>>,
    /// Absolute Uniform Resource Locator, conforming with the \"absolute-URI\" production specified in IETF RFC 3986, section 4.3 in which the scheme part is \"http\" or \"https\". Note that the \"query\" suffix is permitted by this production but the \"fragment\" suffix is not.
    #[serde(rename = "notficationURL", skip_serializing_if = "Option::is_none")]
    pub notfication_url: Option<String>,
}

impl NetworkAssistanceSession {
    /// A representation of a Network Assistance Session resource.
    pub fn new(na_session_id: String, provisioning_session_id: String, service_data_flow_descriptions: Vec<crate::models::ServiceDataFlowDescription>) -> NetworkAssistanceSession {
        NetworkAssistanceSession {
            na_session_id,
            provisioning_session_id,
            service_data_flow_descriptions,
            media_type: None,
            policy_template_id: None,
            requested_qo_s: None,
            recommended_qo_s: None,
            notfication_url: None,
        }
    }
}


