/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// NsmfEventExposureNotification : Represents notifications on events that occurred.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NsmfEventExposureNotification {
    /// Notification correlation ID
    #[serde(rename = "notifId")]
    pub notif_id: String,
    /// Notifications about Individual Events
    #[serde(rename = "eventNotifs")]
    pub event_notifs: Vec<crate::models::EventNotification>,
    /// String providing an URI formatted according to RFC 3986.
    #[serde(rename = "ackUri", skip_serializing_if = "Option::is_none")]
    pub ack_uri: Option<String>,
}

impl NsmfEventExposureNotification {
    /// Represents notifications on events that occurred.
    pub fn new(notif_id: String, event_notifs: Vec<crate::models::EventNotification>) -> NsmfEventExposureNotification {
        NsmfEventExposureNotification {
            notif_id,
            event_notifs,
            ack_uri: None,
        }
    }
}


