/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PduSessionInformation : Represents the PDU session related information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PduSessionInformation {
    /// Unsigned integer identifying a PDU session, within the range 0 to 255, as specified in  clause 11.2.3.1b, bits 1 to 8, of 3GPP TS 24.007. If the PDU Session ID is allocated by the  Core Network for UEs not supporting N1 mode, reserved range 64 to 95 is used. PDU Session ID  within the reserved range is only visible in the Core Network.  
    #[serde(rename = "pduSessId", skip_serializing_if = "Option::is_none")]
    pub pdu_sess_id: Option<i32>,
    #[serde(rename = "sessInfo", skip_serializing_if = "Option::is_none")]
    pub sess_info: Option<Box<crate::models::PduSessionInfo>>,
}

impl PduSessionInformation {
    /// Represents the PDU session related information.
    pub fn new() -> PduSessionInformation {
        PduSessionInformation {
            pdu_sess_id: None,
            sess_info: None,
        }
    }
}


