/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PduSessionInfo : Represents session information.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PduSessionInfo {
    /// The identifier of the N4 session for the reported PDU Session.
    #[serde(rename = "n4SessId", skip_serializing_if = "Option::is_none")]
    pub n4_sess_id: Option<String>,
    /// indicating a time in seconds.
    #[serde(rename = "sessInactiveTimer", skip_serializing_if = "Option::is_none")]
    pub sess_inactive_timer: Option<i32>,
    #[serde(rename = "pduSessStatus", skip_serializing_if = "Option::is_none")]
    pub pdu_sess_status: Option<Box<crate::models::PduSessionStatus>>,
}

impl PduSessionInfo {
    /// Represents session information.
    pub fn new() -> PduSessionInfo {
        PduSessionInfo {
            n4_sess_id: None,
            sess_inactive_timer: None,
            pdu_sess_status: None,
        }
    }
}


