/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PduSessionType : PduSessionType indicates the type of a PDU session. It shall comply with the provisions defined in table 5.4.3.3-1.  



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PduSessionType {
}

impl PduSessionType {
    /// PduSessionType indicates the type of a PDU session. It shall comply with the provisions defined in table 5.4.3.3-1.  
    pub fn new() -> PduSessionType {
        PduSessionType {
        }
    }
}


