/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PduSessionStatus : Possible values are: - ACTIVATED: PDU Session status is activated. - DEACTIVATED: PDU Session status is deactivated.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PduSessionStatus {
}

impl PduSessionStatus {
    /// Possible values are: - ACTIVATED: PDU Session status is activated. - DEACTIVATED: PDU Session status is deactivated.
    pub fn new() -> PduSessionStatus {
        PduSessionStatus {
        }
    }
}


