/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PerUeAttribute : UE application data collected per UE.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerUeAttribute {
    #[serde(rename = "ueDest", skip_serializing_if = "Option::is_none")]
    pub ue_dest: Option<Box<crate::models::LocationArea5G>>,
    #[serde(rename = "route", skip_serializing_if = "Option::is_none")]
    pub route: Option<String>,
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
    #[serde(rename = "avgSpeed", skip_serializing_if = "Option::is_none")]
    pub avg_speed: Option<String>,
    /// string with format 'date-time' as defined in OpenAPI.
    #[serde(rename = "timeOfArrival", skip_serializing_if = "Option::is_none")]
    pub time_of_arrival: Option<String>,
}

impl PerUeAttribute {
    /// UE application data collected per UE.
    pub fn new() -> PerUeAttribute {
        PerUeAttribute {
            ue_dest: None,
            route: None,
            avg_speed: None,
            time_of_arrival: None,
        }
    }
}


