/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PerformanceData : Contains Performance Data.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceData {
    /// Unsigned integer indicating Packet Delay Budget (see clauses 5.7.3.4 and 5.7.4 of 3GPP TS 23.501), expressed in milliseconds. 
    #[serde(rename = "pdb", skip_serializing_if = "Option::is_none")]
    pub pdb: Option<i32>,
    /// Unsigned integer indicating Packet Loss Rate (see clauses 5.7.2.8 and 5.7.4 of 3GPP TS 23.501), expressed in tenth of percent. 
    #[serde(rename = "plr", skip_serializing_if = "Option::is_none")]
    pub plr: Option<i32>,
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
    #[serde(rename = "thrputUl", skip_serializing_if = "Option::is_none")]
    pub thrput_ul: Option<String>,
    /// String representing a bit rate; the prefixes follow the standard symbols from The International System of Units, and represent x1000 multipliers, with the exception that prefix \"K\" is used to represent the standard symbol \"k\". 
    #[serde(rename = "thrputDl", skip_serializing_if = "Option::is_none")]
    pub thrput_dl: Option<String>,
}

impl PerformanceData {
    /// Contains Performance Data.
    pub fn new() -> PerformanceData {
        PerformanceData {
            pdb: None,
            plr: None,
            thrput_ul: None,
            thrput_dl: None,
        }
    }
}


