/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PointUncertaintyCircle : Ellipsoid point with uncertainty circle.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PointUncertaintyCircle {
    #[serde(rename = "shape")]
    pub shape: Box<crate::models::SupportedGadShapes>,
    #[serde(rename = "point")]
    pub point: Box<crate::models::GeographicalCoordinates>,
    /// Indicates value of uncertainty.
    #[serde(rename = "uncertainty")]
    pub uncertainty: f32,
}

impl PointUncertaintyCircle {
    /// Ellipsoid point with uncertainty circle.
    pub fn new(shape: crate::models::SupportedGadShapes, point: crate::models::GeographicalCoordinates, uncertainty: f32) -> PointUncertaintyCircle {
        PointUncertaintyCircle {
            shape: Box::new(shape),
            point: Box::new(point),
            uncertainty,
        }
    }
}


