/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RatType : Indicates the radio access used.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RatType {
}

impl RatType {
    /// Indicates the radio access used.
    pub fn new() -> RatType {
        RatType {
        }
    }
}


