/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ReachabilityFilter : Event filter for REACHABILITY_REPORT event type



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReachabilityFilter {
}

impl ReachabilityFilter {
    /// Event filter for REACHABILITY_REPORT event type
    pub fn new() -> ReachabilityFilter {
        ReachabilityFilter {
        }
    }
}


