/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// RmInfo : Represents the registration state of a UE for an access type



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RmInfo {
    #[serde(rename = "rmState")]
    pub rm_state: Box<crate::models::RmState>,
    #[serde(rename = "accessType")]
    pub access_type: crate::models::AccessType,
}

impl RmInfo {
    /// Represents the registration state of a UE for an access type
    pub fn new(rm_state: crate::models::RmState, access_type: crate::models::AccessType) -> RmInfo {
        RmInfo {
            rm_state: Box::new(rm_state),
            access_type,
        }
    }
}


