/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServiceExperienceInfoPerFlow : Contains service experience information associated with a service flow.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceExperienceInfoPerFlow {
    #[serde(rename = "svcExprc", skip_serializing_if = "Option::is_none")]
    pub svc_exprc: Option<Box<crate::models::SvcExperience>>,
    #[serde(rename = "timeIntev", skip_serializing_if = "Option::is_none")]
    pub time_intev: Option<Box<crate::models::TimeWindow>>,
    /// DNAI (Data network access identifier), see clause 5.6.7 of 3GPP TS 23.501.
    #[serde(rename = "dnai", skip_serializing_if = "Option::is_none")]
    pub dnai: Option<String>,
    #[serde(rename = "ipTrafficFilter", skip_serializing_if = "Option::is_none")]
    pub ip_traffic_filter: Option<Box<crate::models::FlowInfo>>,
    #[serde(rename = "ethTrafficFilter", skip_serializing_if = "Option::is_none")]
    pub eth_traffic_filter: Option<Box<crate::models::EthFlowDescription>>,
}

impl ServiceExperienceInfoPerFlow {
    /// Contains service experience information associated with a service flow.
    pub fn new() -> ServiceExperienceInfoPerFlow {
        ServiceExperienceInfoPerFlow {
            svc_exprc: None,
            time_intev: None,
            dnai: None,
            ip_traffic_filter: None,
            eth_traffic_filter: None,
        }
    }
}


