/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServiceExperienceInfo : Contains service experience information associated with an application.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceExperienceInfo {
    /// String providing an application identifier.
    #[serde(rename = "appId", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    #[serde(rename = "supis", skip_serializing_if = "Option::is_none")]
    pub supis: Option<Vec<String>>,
    #[serde(rename = "svcExpPerFlows")]
    pub svc_exp_per_flows: Vec<crate::models::ServiceExperienceInfoPerFlow>,
}

impl ServiceExperienceInfo {
    /// Contains service experience information associated with an application.
    pub fn new(svc_exp_per_flows: Vec<crate::models::ServiceExperienceInfoPerFlow>) -> ServiceExperienceInfo {
        ServiceExperienceInfo {
            app_id: None,
            supis: None,
            svc_exp_per_flows,
        }
    }
}


