/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SmNasFromUe : Represents information on the SM NAS messages that SMF receives from UE for PDU Session. 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SmNasFromUe {
    #[serde(rename = "smNasType")]
    pub sm_nas_type: String,
    /// string with format 'date-time' as defined in OpenAPI.
    #[serde(rename = "timeStamp")]
    pub time_stamp: String,
}

impl SmNasFromUe {
    /// Represents information on the SM NAS messages that SMF receives from UE for PDU Session. 
    pub fn new(sm_nas_type: String, time_stamp: String) -> SmNasFromUe {
        SmNasFromUe {
            sm_nas_type,
            time_stamp,
        }
    }
}


