/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SupportedSnssai : Supported S-NSSAIs



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportedSnssai {
    #[serde(rename = "sNssai")]
    pub s_nssai: Box<crate::models::ExtSnssai>,
    #[serde(rename = "restrictionInd", skip_serializing_if = "Option::is_none")]
    pub restriction_ind: Option<bool>,
}

impl SupportedSnssai {
    /// Supported S-NSSAIs
    pub fn new(s_nssai: crate::models::ExtSnssai) -> SupportedSnssai {
        SupportedSnssai {
            s_nssai: Box::new(s_nssai),
            restriction_ind: None,
        }
    }
}


