/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SvcExperience : Contains a mean opinion score with the customized range.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SvcExperience {
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "mos", skip_serializing_if = "Option::is_none")]
    pub mos: Option<f32>,
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "upperRange", skip_serializing_if = "Option::is_none")]
    pub upper_range: Option<f32>,
    /// string with format 'float' as defined in OpenAPI.
    #[serde(rename = "lowerRange", skip_serializing_if = "Option::is_none")]
    pub lower_range: Option<f32>,
}

impl SvcExperience {
    /// Contains a mean opinion score with the customized range.
    pub fn new() -> SvcExperience {
        SvcExperience {
            mos: None,
            upper_range: None,
            lower_range: None,
        }
    }
}


