/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TacRange : Range of TACs (Tracking Area Codes)



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TacRange {
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<String>,
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
}

impl TacRange {
    /// Range of TACs (Tracking Area Codes)
    pub fn new() -> TacRange {
        TacRange {
            start: None,
            end: None,
            pattern: None,
        }
    }
}


