/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TargetUeIdentification : Identifies the UE to which the request applies.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TargetUeIdentification {
    #[serde(rename = "supis", skip_serializing_if = "Option::is_none")]
    pub supis: Option<Vec<String>>,
    #[serde(rename = "interGroupIds", skip_serializing_if = "Option::is_none")]
    pub inter_group_ids: Option<Vec<String>>,
    #[serde(rename = "anyUeId", skip_serializing_if = "Option::is_none")]
    pub any_ue_id: Option<bool>,
}

impl TargetUeIdentification {
    /// Identifies the UE to which the request applies.
    pub fn new() -> TargetUeIdentification {
        TargetUeIdentification {
            supis: None,
            inter_group_ids: None,
            any_ue_id: None,
        }
    }
}


