/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TimeWindow : Represents a time window identified by a start time and a stop time.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeWindow {
    /// string with format \"date-time\" as defined in OpenAPI.
    #[serde(rename = "startTime")]
    pub start_time: String,
    /// string with format \"date-time\" as defined in OpenAPI.
    #[serde(rename = "stopTime")]
    pub stop_time: String,
}

impl TimeWindow {
    /// Represents a time window identified by a start time and a stop time.
    pub fn new(start_time: String, stop_time: String) -> TimeWindow {
        TimeWindow {
            start_time,
            stop_time,
        }
    }
}


