/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// TransportProtocol : Possible values are: - UDP: User Datagram Protocol. - TCP: Transmission Control Protocol.  



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransportProtocol {
}

impl TransportProtocol {
    /// Possible values are: - UDP: User Datagram Protocol. - TCP: Transmission Control Protocol.  
    pub fn new() -> TransportProtocol {
        TransportProtocol {
        }
    }
}


