/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UeLocationTrendsReportItem : Report Item for UE Location Trends event.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UeLocationTrendsReportItem {
    #[serde(rename = "tai", skip_serializing_if = "Option::is_none")]
    pub tai: Option<Box<crate::models::Tai>>,
    #[serde(rename = "ncgi", skip_serializing_if = "Option::is_none")]
    pub ncgi: Option<Box<crate::models::Ncgi>>,
    #[serde(rename = "ecgi", skip_serializing_if = "Option::is_none")]
    pub ecgi: Option<Box<crate::models::Ecgi>>,
    #[serde(rename = "n3gaLocation", skip_serializing_if = "Option::is_none")]
    pub n3ga_location: Option<Box<crate::models::N3gaLocation>>,
    /// indicating a time in seconds.
    #[serde(rename = "spacing")]
    pub spacing: i32,
    /// indicating a time in seconds.
    #[serde(rename = "duration")]
    pub duration: i32,
    /// string with format 'date-time' as defined in OpenAPI.
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl UeLocationTrendsReportItem {
    /// Report Item for UE Location Trends event.
    pub fn new(spacing: i32, duration: i32, timestamp: String) -> UeLocationTrendsReportItem {
        UeLocationTrendsReportItem {
            tai: None,
            ncgi: None,
            ecgi: None,
            n3ga_location: None,
            spacing,
            duration,
            timestamp,
        }
    }
}


