/*
 * Namf_EventExposure
 *
 * AMF Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.3
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UeReachability : Describes the reachability of the UE



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UeReachability {
}

impl UeReachability {
    /// Describes the reachability of the UE
    pub fn new() -> UeReachability {
        UeReachability {
        }
    }
}


