/*
 * Nsmf_EventExposure
 *
 * Session Management Event Exposure Service.   © 2023, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.2
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UpfInformation : Represents the ID/address/FQDN of the UPF.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpfInformation {
    #[serde(rename = "upfId", skip_serializing_if = "Option::is_none")]
    pub upf_id: Option<String>,
    #[serde(rename = "upfAddr", skip_serializing_if = "Option::is_none")]
    pub upf_addr: Option<Box<crate::models::AddrFqdn>>,
}

impl UpfInformation {
    /// Represents the ID/address/FQDN of the UPF.
    pub fn new() -> UpfInformation {
        UpfInformation {
            upf_id: None,
            upf_addr: None,
        }
    }
}


