/*
 * Nnef_EventExposure
 *
 * NEF Event Exposure Service.   © 2022 , 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// UsageThreshold : Represents a usage threshold.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsageThreshold {
    /// Unsigned integer identifying a period of time in units of seconds.
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// Unsigned integer identifying a volume in units of bytes.
    #[serde(rename = "totalVolume", skip_serializing_if = "Option::is_none")]
    pub total_volume: Option<i64>,
    /// Unsigned integer identifying a volume in units of bytes.
    #[serde(rename = "downlinkVolume", skip_serializing_if = "Option::is_none")]
    pub downlink_volume: Option<i64>,
    /// Unsigned integer identifying a volume in units of bytes.
    #[serde(rename = "uplinkVolume", skip_serializing_if = "Option::is_none")]
    pub uplink_volume: Option<i64>,
}

impl UsageThreshold {
    /// Represents a usage threshold.
    pub fn new() -> UsageThreshold {
        UsageThreshold {
            duration: None,
            total_volume: None,
            downlink_volume: None,
            uplink_volume: None,
        }
    }
}


